language: java
sudo: false
dist: trusty

os:
- linux
- osx

jdk:
- openjdk9
- openjdk10

matrix:
  include:
  - os: linux
    jdk: openjdk8

before_script:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version
  - ./mvnw -B -e clean test